
set -g mouse on

# vi for copy mode
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -g base-index 1
setw -g pane-base-index 1
bind-key -T root M-0 select-window -t :=0

bind  c  new-window	 -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8

# https://stackoverflow.com/questions/76345442/why-are-my-alacritty-vim-colors-different-than-iterm2
#set -sg terminal-overrides ",*:RGB"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"  # <- this did a trick for me

set -g status-position top
set -g status-style "fg=#665c54"
set -g status-right ""
set -g status-style bg="#1b1b1b"
# detect operating system and source the appropriate config file
if-shell 'uname -s | grep -q Darwin' 'source-file ~/.tmux.conf.mac'




